inherit_from:
  - .rubocop_airbnb.yml

# Rails最適化
Rails:
   Enabled: true

LineLength:
  Max: 130

Rails/HelperInstanceVariable:
  Enabled: false

#検証除外フォルダ指定
AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'spec/rails_helper.rb'
