# YMLファイルのバージョンを指定
version: '3'

# サービスの定義
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    restart: always
    environment:
      DOMAINS: 'localhost -> http://host.docker.internal:3000'
      STAGE: local
    volumes:
      - './org-chimata-ssl-certs:/var/lib/https-portal'
  # サービス1
  web:
      image: nginx:1.17-alpine
      # 同じディレクトリ配下にあるDockerfileをビルド
      build: .
      # rails実行(s->serverの略)
      command:  /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
      # ローカルPCのディレクトリをrubyコンテナにマウント
      volumes:
          - .:/app
          - /app/tmp/cache
          - /app/node_modules
      # アプリ公開ポートを指定<公開ポート番号>:<コンテナ内の転送先ポート>
      ports:
          - 3000:3000
      # データベースを先に起動してからwebserverを起動
      depends_on:
          - db
      tty: true
      stdin_open: true
    # selenium_chrome を使うために以下の行を追加
      environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
  selenium_chrome:
      image: selenium/standalone-chrome-debug
      logging:
        driver: none
  #サービス2
  db:
      image: mysql:5.7
      # rubyコンテナの/var/lib/mysqlにマウント
      volumes:
          - post-volume:/var/lib/mysql
      # mysqlのルートパスワードを設定するための環境変数
      environment:
          MYSQL_ROOT_PASSWORD: password

# マウントするデータ領域を指定
volumes:
    post-volume:
